# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - myAwesomeApp4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_76793aa57aa6454794ea6a97d69d043d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9570a44c260e4515992478a2b45fd51c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_76793aa57aa6454794ea6a97d69d043d }}/awesome:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myAwesomeApp4'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a606221dd3ce46afa0eaa14388c33788 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_76793aa57aa6454794ea6a97d69d043d }}/awesome:${{ github.sha }}'